schema_version: 1

context:
  name: anchor-exp
  version: 0.0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/anchor_exp-${{ version }}.tar.gz
  sha256: de233047012e75cc0d4302ae85596932e95a5792ef23dcc5aab33361ceadc65b

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy
    - spacy
    - lime
    - scikit-learn >=0.22

tests:
  - python:
      imports:
        - anchor
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Anchor explanations for machine learning models
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: http://github.com/marcotcr/anchor

extra:
  recipe-maintainers:
    - rxm7706
